from datetime import datetime

from pydantic import BaseModel


class IdentityFacts(BaseModel):
    """Deterministic facts pulled from every module — the ONLY thing the
    synthesis LLM call (identity_synthesizer.py) is allowed to reason
    over. Nothing in this object is LLM-generated, EXCEPT role_fit, which
    is deliberately, entirely LLM-generated by services/identity/role_fit.py
    (Engineering Identity fix #2) — it is stored here as a fact only in
    the sense that it's already been computed once and shouldn't be
    recomputed a second, disagreeing way downstream.
    """
    top_skills: list[dict] = []                    # {"skill","confidence","sources","corroboration_count"}
    role_fit: list[dict] = []                       # {"role","rating","rationale"} — LLM-generated, see above
    resume_score: float | None = None
    resume_grade: str | None = None
    github_summary: dict = {}
    github_progress: dict = {}
    architecture_maturity: dict = {}
    technology_depth_highlights: list[dict] = []     # top N by depth score
    technology_breadth: dict = {}                    # NEW (fix #9) — total distinct techs, depth-vs-breadth
    leetcode_summary: dict = {}
    leetcode_topic_mastery: list[dict] = []
    engineering_quadrant: dict | None = None         # NEW (fix #5) — LeetCode x GitHub interview-readiness quadrant
    company_readiness: list[dict] = []               # NEW (fix #5) — top company-readiness entries
    coverage_gaps: dict = {}
    timeline_plausibility_notes: list[dict] = []
    active_goals: list[dict] = []
    recent_job_matches: list[dict] = []
    claim_risk_details: list[dict] = []              # RENAMED from claim_risk_summary (fix #4) — real,
                                                      # per-project {"project","risk_level","headline"} entries
                                                      # instead of a lossy {"high_risk_count","medium_risk_count"}


class IdentityLLMOutput(BaseModel):
    headline: str = ""
    summary: str = ""
    strongest_signals: list[str] = []
    biggest_gaps: list[str] = []
    contradictions: list[str] = []
    recommended_focus: str = ""


class EngineeringIdentityReport(BaseModel):
    facts: IdentityFacts
    narrative: IdentityLLMOutput
    generated_at: datetime | None = None
    analysis_degraded: bool = False