"""Builds the deterministic IdentityFacts object — the ONLY input the
Engineering Identity synthesis LLM call (identity_synthesizer.py) is
allowed to reason over (with the one deliberate exception of role_fit,
which is itself LLM-generated by services/identity/role_fit.py — see
Engineering Identity fix #2). Pulls from every module that already
computes real, verified facts: Resume Analysis Engine, the unified skill
evidence pool, GitHub knowledge (including architecture_maturity and
technology_depth), LeetCode knowledge, the LeetCode x GitHub Engineering
Maturity Quadrant, cross-source coverage gaps, timeline plausibility,
active goals, and recent job-match history.
"""
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.facts import JobDescription, Resume, Project
from app.models.goals import Goal
from app.models.inference import ResumeAnalysis, SkillEvidence, ProjectClaimAuditReview
from app.models.structure import Skill
from app.schemas.engineering_identity import IdentityFacts
from app.services.evidence import build_evidence_details, get_all_skill_confidences
from app.services.github.github_knowledge import build_github_knowledge_object
from app.services.identity.role_fit import get_role_fit
from app.services.identity.role_fit_scoping import build_scoped_skill_evidence
from app.services.leetcode.engineering_snapshot import compute_engineering_snapshot
from app.services.leetcode.leetcode_knowledge import build_leetcode_knowledge_object
from app.services.resume.analysis.coverage import analyze_cross_source_coverage
from app.services.resume.confidence import compute_corroboration_count
from app.services.resume.analysis.role_fit import ROLE_ARCHETYPES  # kept only as a valid-role reference if needed

MAX_TOP_SKILLS = 10
MAX_TECH_DEPTH_HIGHLIGHTS = 6
MAX_RECENT_JOB_MATCHES = 3
MAX_COMPANY_READINESS_ENTRIES = 5

# github_skill_depth.py's own "Working proficiency"+ floor — reused here
# so technology_breadth's "deep_or_better_count" (fix #9) can't silently
# drift from what that module itself calls "deep".
DEEP_OR_BETTER_DEPTH_FLOOR = 55


async def _get_top_skills(db: AsyncSession, limit: int = MAX_TOP_SKILLS) -> list[dict]:
    confidences = await get_all_skill_confidences(db)
    if not confidences:
        return []

    ranked = sorted(confidences.items(), key=lambda kv: kv[1], reverse=True)[:limit]
    canonical_names = [c for c, _ in ranked]

    skill_rows = await db.execute(select(Skill).where(Skill.canonical_name.in_(canonical_names)))
    skills_by_canonical = {s.canonical_name: s for s in skill_rows.scalars().all()}

    out = []
    for canonical, confidence in ranked:
        skill = skills_by_canonical.get(canonical)
        sources: list[str] = []
        corroboration_count = 0
        if skill is not None:
            ev_result = await db.execute(select(SkillEvidence).where(SkillEvidence.skill_id == skill.id))
            evidence_rows = list(ev_result.scalars().all())
            sources = await build_evidence_details(db, evidence_rows)
            # Fix #8 — a distinct signal from confidence: how many
            # INDEPENDENT source TYPES back this skill, not how strong
            # the evidence is numerically.
            corroboration_count = compute_corroboration_count(evidence_rows)
        out.append({
            "skill": canonical,
            "confidence": round(confidence, 2),
            "sources": sources,
            "corroboration_count": corroboration_count,
        })
    return out


async def _get_latest_resume(db: AsyncSession, user_id) -> Resume | None:
    result = await db.execute(
        select(Resume).where(Resume.user_id == user_id).order_by(Resume.created_at.desc()).limit(1)
    )
    return result.scalar_one_or_none()


async def _get_latest_resume_analysis(db: AsyncSession, user_id) -> dict | None:
    result = await db.execute(
        select(ResumeAnalysis)
        .where(ResumeAnalysis.user_id == user_id)
        .order_by(ResumeAnalysis.created_at.desc())
        .limit(1)
    )
    row = result.scalar_one_or_none()
    return row.analysis_json if row else None


async def _get_active_goals(db: AsyncSession, user_id) -> list[dict]:
    result = await db.execute(
        select(Goal)
        .where(Goal.user_id == user_id)
        .where(Goal.status_pct < 100.0)
        .order_by(Goal.deadline.asc().nullslast())
    )
    return [
        {
            "title": g.title,
            "deadline": g.deadline.isoformat() if g.deadline else None,
            "priority": g.priority,
            "status_pct": g.status_pct,
        }
        for g in result.scalars().all()
    ]


async def _get_recent_job_matches(db: AsyncSession, user_id, limit: int = MAX_RECENT_JOB_MATCHES) -> list[dict]:
    result = await db.execute(
        select(JobDescription)
        .where(JobDescription.user_id == user_id)
        .where(JobDescription.analysis_result.isnot(None))
        .order_by(JobDescription.created_at.desc())
        .limit(limit)
    )
    out = []
    for jd in result.scalars().all():
        overall = (jd.analysis_result or {}).get("overall_match", {})
        out.append({
            "role": jd.role,
            "company": jd.company,
            "match_percentage": overall.get("percentage"),
            "match_label": overall.get("label"),
        })
    return out


async def _get_claim_risk_details(db: AsyncSession, user_id) -> list[dict]:
    """Real, per-project claim-risk findings — Engineering Identity
    fix #4. Previously this only counted {"high_risk_count",
    "medium_risk_count"}, discarding the specific project names and
    headlines ProjectClaimAuditReview already has (the same rows
    projects/portfolio_narrative.py already reads for its own
    claim_audit_risk_distribution). Reusing that shape here is what lets
    identity_synthesizer's "contradictions" field cite something specific
    (e.g. "Cortex Route claims Kubernetes with no supporting evidence")
    instead of a bare count.
    """
    proj_result = await db.execute(select(Project.id, Project.name).where(Project.user_id == user_id))
    projects_by_id = {pid: name for pid, name in proj_result.all()}
    if not projects_by_id:
        return []
    audit_result = await db.execute(
        select(ProjectClaimAuditReview).where(ProjectClaimAuditReview.project_id.in_(projects_by_id.keys()))
    )
    details: list[dict] = []
    for row in audit_result.scalars().all():
        narrative = (row.report_json or {}).get("narrative", {})
        level = narrative.get("risk_level", "low")
        if level in ("high", "medium"):
            details.append({
                "project": projects_by_id.get(row.project_id, "Unknown project"),
                "risk_level": level,
                "headline": narrative.get("headline", ""),
            })
    return details


def _build_technology_breadth(github_knowledge: dict) -> dict:
    """Fix #9 — previously IdentityFacts only ever carried the top 6
    technology_depth_highlights, so the synthesizer had no way to
    distinguish "deep in 2 technologies, broad across 14 others" from
    "deep and narrow" — the input simply didn't contain the information
    needed to say either. This adds that missing breadth signal.
    """
    all_technologies = github_knowledge.get("all_technologies", [])
    technology_depth = github_knowledge.get("technology_depth", {})
    deep_or_better_count = sum(
        1 for d in technology_depth.values() if isinstance(d, dict) and d.get("score", 0) >= DEEP_OR_BETTER_DEPTH_FLOOR
    )
    return {
        "total_distinct_technologies": len(all_technologies),
        "technologies_with_depth_data": len(technology_depth),
        "deep_or_better_count": deep_or_better_count,
    }


async def build_identity_facts(db: AsyncSession, user_id) -> IdentityFacts:
    top_skills = await _get_top_skills(db)

    # Role-fit — deliberately, entirely LLM-generated (fix #2). Uses the
    # user's ALL-SOURCES evidence pool, same real confidence numbers
    # top_skills is built from.
    all_sources_evidence = await build_scoped_skill_evidence(db, source_types=None)
    role_fit_results = await get_role_fit(all_sources_evidence, scope="all_sources")
    role_fit = [r.model_dump() for r in role_fit_results]

    resume_analysis = await _get_latest_resume_analysis(db, user_id)
    resume_score = resume_analysis.get("overall_score") if resume_analysis else None
    resume_grade = resume_analysis.get("grade") if resume_analysis else None

    # --- Fix #6: compute github_knowledge and the engineering snapshot
    # EXACTLY ONCE each, then pass them into build_leetcode_knowledge_object
    # instead of letting it silently re-fetch/recompute both internally
    # (which is what it does when called standalone, e.g. by
    # leetcode_reviewer.py — this call site opts into the precomputed path). ---
    github_knowledge = await build_github_knowledge_object(db, user_id) or {}
    engineering_snapshot = await compute_engineering_snapshot(db, user_id)

    github_summary = github_knowledge.get("summary", {})
    github_progress = github_knowledge.get("progress", {})
    architecture_maturity = github_knowledge.get("architecture_maturity", {})

    technology_depth = github_knowledge.get("technology_depth", {})
    technology_depth_highlights = sorted(
        [{"technology": tech, **data} for tech, data in technology_depth.items()],
        key=lambda d: d.get("score", 0),
        reverse=True,
    )[:MAX_TECH_DEPTH_HIGHLIGHTS]
    technology_breadth = _build_technology_breadth(github_knowledge)

    leetcode_knowledge = await build_leetcode_knowledge_object(
        db, user_id, github_knowledge=github_knowledge, engineering_snapshot=engineering_snapshot,
    ) or {}
    leetcode_summary = leetcode_knowledge.get("leetcode_summary", {})
    leetcode_topic_mastery = leetcode_knowledge.get("topic_mastery", [])

    # --- Fix #5: surface the LeetCode x GitHub Engineering Maturity
    # Quadrant + company readiness — previously computed but dropped on
    # the floor between here and IdentityFacts. ---
    engineering_quadrant = None
    company_readiness: list[dict] = []
    if engineering_snapshot is not None:
        engineering_quadrant = {
            "leetcode_score": engineering_snapshot["leetcode_score"],
            "github_score": engineering_snapshot["github_score"],
            "quadrant_label": engineering_snapshot["quadrant_label"],
            "description": engineering_snapshot["description"],
        }
        company_readiness = engineering_snapshot.get("company_readiness", [])[:MAX_COMPANY_READINESS_ENTRIES]

    latest_resume = await _get_latest_resume(db, user_id)
    coverage_gaps: dict = {}
    timeline_plausibility_notes: list[dict] = []
    if latest_resume is not None:
        coverage_gaps = await analyze_cross_source_coverage(db, user_id, latest_resume.id)
        timeline_plausibility_notes = coverage_gaps.get("timeline_plausibility_notes", [])

    active_goals = await _get_active_goals(db, user_id)
    recent_job_matches = await _get_recent_job_matches(db, user_id)
    claim_risk_details = await _get_claim_risk_details(db, user_id)

    return IdentityFacts(
        top_skills=top_skills,
        role_fit=role_fit,
        resume_score=resume_score,
        resume_grade=resume_grade,
        github_summary=github_summary,
        github_progress=github_progress,
        architecture_maturity=architecture_maturity,
        technology_depth_highlights=technology_depth_highlights,
        technology_breadth=technology_breadth,
        leetcode_summary=leetcode_summary,
        leetcode_topic_mastery=leetcode_topic_mastery,
        engineering_quadrant=engineering_quadrant,
        company_readiness=company_readiness,
        coverage_gaps={k: v for k, v in coverage_gaps.items() if k != "timeline_plausibility_notes"},
        timeline_plausibility_notes=timeline_plausibility_notes,
        active_goals=active_goals,
        recent_job_matches=recent_job_matches,
        claim_risk_details=claim_risk_details,
    )