# -*- coding: utf-8 -*-
"""Builds the deterministic IdentityFacts object — the ONLY input the
Engineering Identity synthesis LLM call (identity_synthesizer.py) is
allowed to reason over (with the one deliberate exception of role_fit,
which is itself LLM-generated by services/identity/role_fit.py). Pulls
from every module that already computes real, verified facts.

Reconciliation fix (Critical, Engineering Identity audit): top_skills'
confidence numbers are now produced by the single shared, unbounded
services/identity/reconciled_confidence.get_reconciled_skill_confidences()
— claim-risk / timeline-plausibility reconciliation happens exactly
once, there, and this module just takes the top-N slice of it. The
Skill Gap Analyzer (services/skill_gap/comparison.py) reads from the exact same function, so a skill's confidence can never disagree between GET /identity and GET /jobs/{id} again.

Role-fit caching fix: the all_sources role_fit LLM call is skipped and
reused from the previous EngineeringIdentity snapshot whenever the
underlying scoped skill evidence hasn't actually changed — see
_compute_evidence_hash / _get_cached_role_fit below.

Recency + completeness fix (audit findings #1/#2): source_freshness and
evidence_coverage are now computed alongside everything else — see
freshness.py. Neither is derived from any of the OTHER facts here; both
read timestamps directly, independent of whether a given source
happened to have anything interesting to say this time.
"""

import hashlib
import json

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.facts import JobDescription, Resume, Project
from app.models.goals import Goal
from app.models.inference import (
    ResumeAnalysis,
    SkillEvidence,
    ProjectClaimAuditReview,
    EngineeringIdentity,
)
from app.models.structure import Skill
from app.schemas.identity.engineering_identity import IdentityFacts, PortfolioNarrativeFacts
from app.services.evidence import build_evidence_details, get_all_skill_confidences
from app.services.github.github_knowledge import build_github_knowledge_object
# from app.services.identity.confidence_reconciliation import reconcile_skill_confidence
from app.services.identity.freshness import compute_evidence_coverage, compute_source_freshness
from app.services.identity.role_fit import get_role_fit
from app.services.identity.role_fit_scoping import build_scoped_skill_evidence
from app.services.leetcode.engineering_snapshot import compute_engineering_snapshot
from app.services.leetcode.leetcode_knowledge import build_leetcode_knowledge_object
from app.services.projects.portfolio_narrative import get_latest_portfolio_narrative
from app.services.resume.analysis.coverage import analyze_cross_source_coverage
from app.services.resume.confidence import compute_corroboration_count
from app.services.resume.analysis.role_fit import ROLE_ARCHETYPES  # kept only as a valid-role reference
# New imports for reconciled confidence
from app.services.identity.reconciled_confidence import (
    get_claim_risk_details,
    get_reconciled_skill_confidences,
)

MAX_TOP_SKILLS = 10
MAX_TECH_DEPTH_HIGHLIGHTS = 6
MAX_RECENT_JOB_MATCHES = 3
MAX_COMPANY_READINESS_ENTRIES = 5

DEEP_OR_BETTER_DEPTH_FLOOR = 55


# --- Top skills implementation -------------------------------------------------
async def _get_top_skills(db: AsyncSession, user_id, limit: int = MAX_TOP_SKILLS) -> list[dict]:
    """Top-N reconciled skills, sorted by (already-reconciled) confidence
    descending. Delegates entirely to the shared, unbounded
    reconciled_confidence.get_reconciled_skill_confidences() — see that
    module's docstring for why reconciliation is computed once, there,
    instead of being duplicated per top-N-slice caller.

    Note: because reconciliation is now applied BEFORE this slice
    (rather than after, on an already-chosen top-N), a skill whose
    confidence gets discounted below another skill's may no longer make
    the cut. That's intentional — it's the fix for top_skills previously
    being able to show a stale/incorrect confidence number for a
    flagged skill that should have dropped out of the top N entirely.
    """
    reconciled = await get_reconciled_skill_confidences(db, user_id)
    if not reconciled:
        return []
    ranked = sorted(reconciled.values(), key=lambda e: e["confidence"], reverse=True)
    return ranked[:limit]

# --- Legacy top-skills (pre-reconciliation) -------------------------------
# async def _get_top_skills(db: AsyncSession, user_id, limit: int = MAX_TOP_SKILLS) -> list[dict]:
#     """Returns RAW (pre-reconciliation) top skills — confidence here is
#     purely the decayed evidence-weight score. Reconciliation against
#     claim_risk_details/timeline_plausibility_notes happens once, at the
#     end of build_identity_facts(), after both of those are available.
#     """
#     confidences = await get_all_skill_confidences(db, user_id)
#     if not confidences:
#         return []
#     ranked = sorted(confidences.items(), key=lambda kv: kv[1], reverse=True)[:limit]
#     canonical_names = [c for c, _ in ranked]
#     skill_rows = await db.execute(select(Skill).where(Skill.canonical_name.in_(canonical_names)))
#     skills_by_canonical = {s.canonical_name: s for s in skill_rows.scalars().all()}
#     skill_ids = [s.id for s in skills_by_canonical.values()]
#     evidence_by_skill_id: dict = {}
#     if skill_ids:
#         ev_result = await db.execute(
#             select(SkillEvidence).where(
#                 SkillEvidence.skill_id.in_(skill_ids),
#                 SkillEvidence.user_id == user_id,
#             )
#         )
#         for row in ev_result.scalars().all():
#             evidence_by_skill_id.setdefault(row.skill_id, []).append(row)
#     out = []
#     for canonical, confidence in ranked:
#         skill = skills_by_canonical.get(canonical)
#         sources: list[str] = []
#         corroboration_count = 0
#         if skill is not None:
#             evidence_rows = evidence_by_skill_id.get(skill.id, [])
#             sources = await build_evidence_details(db, evidence_rows)
#             corroboration_count = compute_corroboration_count(evidence_rows)
#         out.append({
#             "skill": canonical,
#             "confidence": round(confidence, 2),
#             "sources": sources,
#             "corroboration_count": corroboration_count,
#         })
#     return out

# --- Latest resume helpers ---------------------------------------------------
async def _get_latest_resume(db: AsyncSession, user_id) -> Resume | None:
    result = await db.execute(
        select(Resume).where(Resume.user_id == user_id).order_by(Resume.created_at.desc()).limit(1)
    )
    return result.scalar_one_or_none()

async def _get_latest_resume_analysis(db: AsyncSession, user_id) -> dict | None:
    result = await db.execute(
        select(ResumeAnalysis)
        .where(ResumeAnalysis.user_id == user_id)
        .order_by(ResumeAnalysis.created_at.desc())
        .limit(1)
    )
    row = result.scalar_one_or_none()
    return row.analysis_json if row else None

# --- Active goals -----------------------------------------------------------
async def _get_active_goals(db: AsyncSession, user_id) -> list[dict]:
    result = await db.execute(
        select(Goal)
        .where(Goal.user_id == user_id)
        .where(Goal.status_pct < 100.0)
        .order_by(Goal.deadline.asc().nullslast())
    )
    return [
        {
            "title": g.title,
            "deadline": g.deadline.isoformat() if g.deadline else None,
            "priority": g.priority,
            "status_pct": g.status_pct,
        }
        for g in result.scalars().all()
    ]

# --- Recent job matches ------------------------------------------------------
async def _get_recent_job_matches(db: AsyncSession, user_id, limit: int = MAX_RECENT_JOB_MATCHES) -> list[dict]:
    result = await db.execute(
        select(JobDescription)
        .where(JobDescription.user_id == user_id)
        .where(JobDescription.analysis_result.isnot(None))
        .order_by(JobDescription.created_at.desc())
        .limit(limit)
    )
    out = []
    for jd in result.scalars().all():
        overall = (jd.analysis_result or {}).get("overall_match", {})
        out.append({
            "role": jd.role,
            "company": jd.company,
            "match_percentage": overall.get("percentage"),
            "match_label": overall.get("label"),
        })
    return out

# --- Claim risk details ------------------------------------------------------
async def _get_claim_risk_details(db: AsyncSession, user_id) -> list[dict]:
    """Each entry carries "unsupported_claims" (the real skill/tech
    strings the Claim Audit found with no supporting GitHub evidence),
    which confidence_reconciliation.py relies on to discount the right
    skill's top_skills confidence, not just flag the project.
    """
    proj_result = await db.execute(select(Project.id, Project.name).where(Project.user_id == user_id))
    projects_by_id = {pid: name for pid, name in proj_result.all()}
    if not projects_by_id:
        return []
    audit_result = await db.execute(
        select(ProjectClaimAuditReview).where(ProjectClaimAuditReview.project_id.in_(projects_by_id.keys()))
    )
    details: list[dict] = []
    for row in audit_result.scalars().all():
        report_json = row.report_json or {}
        narrative = report_json.get("narrative", {})
        facts = report_json.get("facts", {})
        level = narrative.get("risk_level", "low")
        if level in ("high", "medium"):
            details.append({
                "project": projects_by_id.get(row.project_id, "Unknown project"),
                "risk_level": level,
                "headline": narrative.get("headline", ""),
                "unsupported_claims": facts.get("unsupported_claims", []),
            })
    return details

# --- Technology breadth helper ------------------------------------------------
def _build_technology_breadth(github_knowledge: dict) -> dict:
    all_technologies = github_knowledge.get("all_technologies", [])
    technology_depth = github_knowledge.get("technology_depth", {})
    deep_or_better_count = sum(
        1 for d in technology_depth.values() if isinstance(d, dict) and d.get("score", 0) >= DEEP_OR_BETTER_DEPTH_FLOOR
    )
    return {
        "total_distinct_technologies": len(all_technologies),
        "technologies_with_depth_data": len(technology_depth),
        "deep_or_better_count": deep_or_better_count,
    }

# --- Evidence hash (new version) --------------------------------------------
def _compute_evidence_hash(evidence: list[dict]) -> str:
    """Stable hash of the all_sources skill evidence used for role_fit.
    Two refreshes with the exact same (skill, confidence) pairs hash
    identically — see _get_cached_role_fit for how this skips a
    redundant LLM call.
    """
    normalized = sorted((e["skill"], round(e.get("confidence", 0.0), 3)) for e in evidence)
    raw = json.dumps(normalized, sort_keys=True)
    return hashlib.sha256(raw.encode()).hexdigest()

# --- Legacy evidence hash (including claim risk & timeline) ---------------
# def _compute_evidence_hash(
#     evidence: list[dict],
#     claim_risk_details: list[dict],
#     timeline_plausibility_notes: list[dict],
# ) -> str:
#     """Stable hash of the all_sources skill evidence PLUS the reconciliation
#     signals (claim_risk_details, timeline_plausibility_notes) used for
#     role_fit cache invalidation.
#     """
#     normalized_evidence = sorted((e["skill"], round(e.get("confidence", 0.0), 3)) for e in evidence)
#     normalized_risks = sorted(
#         (
#             d.get("project", ""),
#             d.get("risk_level", ""),
#             tuple(sorted(d.get("unsupported_claims", []))),
#         )
#         for d in claim_risk_details
#     )
#     normalized_timeline = sorted(n.get("skill", "") for n in timeline_plausibility_notes)
#     raw = json.dumps(
#         {"evidence": normalized_evidence, "risks": normalized_risks, "timeline": normalized_timeline},
#         sort_keys=True,
#     )
#     return hashlib.sha256(raw.encode()).hexdigest()

# --- Cached role_fit ----------------------------------------------------------
async def _get_cached_role_fit(db: AsyncSession, user_id, evidence_hash: str) -> list[dict] | None:
    """Returns the previous snapshot's role_fit if its stored evidence
    hash matches the CURRENT all_sources evidence exactly. Only reads
    the most recent VALID (non-invalidated) snapshot — reusing a rating
    that's since been flagged as known-bad would defeat the point of
    invalidation (audit finding #3).
    """
    result = await db.execute(
        select(EngineeringIdentity)
        .where(EngineeringIdentity.user_id == user_id)
        .where(EngineeringIdentity.is_invalidated.is_(False))
        .order_by(EngineeringIdentity.created_at.desc())
        .limit(1)
    )
    row = result.scalar_one_or_none()
    if row is None or not isinstance(row.facts_json, dict):
        return None
    if row.facts_json.get("role_fit_evidence_hash") != evidence_hash:
        return None
    cached = row.facts_json.get("role_fit")
    return cached if isinstance(cached, list) and cached else None

# --- Build identity facts -----------------------------------------------------
async def build_identity_facts(db: AsyncSession, user_id) -> IdentityFacts:
    top_skills = await _get_top_skills(db, user_id)

    # Compute coverage gaps and timeline plausibility notes first
    latest_resume = await _get_latest_resume(db, user_id)
    coverage_gaps: dict = {}
    timeline_plausibility_notes: list[dict] = []
    if latest_resume is not None:
        coverage_gaps = await analyze_cross_source_coverage(db, user_id, latest_resume.id)
        timeline_plausibility_notes = coverage_gaps.get("timeline_plausibility_notes", [])

    claim_risk_details = await _get_claim_risk_details(db, user_id)

    # Build evidence and compute hash (new version only uses evidence)
    all_sources_evidence = await build_scoped_skill_evidence(db, user_id, source_types=None)
    evidence_hash = _compute_evidence_hash(all_sources_evidence)

    cached_role_fit = await _get_cached_role_fit(db, user_id, evidence_hash)
    if cached_role_fit is not None:
        role_fit = cached_role_fit
    else:
        role_fit_results = await get_role_fit(all_sources_evidence, scope="all_sources")
        role_fit = [r.model_dump() for r in role_fit_results]

    resume_analysis = await _get_latest_resume_analysis(db, user_id)
    resume_score = resume_analysis.get("overall_score") if resume_analysis else None
    resume_grade = resume_analysis.get("grade") if resume_analysis else None

    github_knowledge = await build_github_knowledge_object(db, user_id) or {}
    engineering_snapshot = await compute_engineering_snapshot(db, user_id)

    github_summary = github_knowledge.get("summary", {})
    github_progress = github_knowledge.get("progress", {})
    architecture_maturity = github_knowledge.get("architecture_maturity", {})

    technology_depth = github_knowledge.get("technology_depth", {})
    technology_depth_highlights = sorted(
        [{"technology": tech, **data} for tech, data in technology_depth.items()],
        key=lambda d: d.get("score", 0),
        reverse=True,
    )[:MAX_TECH_DEPTH_HIGHLIGHTS]
    technology_breadth = _build_technology_breadth(github_knowledge)

    leetcode_knowledge = await build_leetcode_knowledge_object(
        db, user_id, github_knowledge=github_knowledge, engineering_snapshot=engineering_snapshot,
    ) or {}
    leetcode_summary = leetcode_knowledge.get("leetcode_summary", {})
    leetcode_topic_mastery = leetcode_knowledge.get("topic_mastery", [])

    engineering_quadrant = None
    company_readiness: list[dict] = []
    if engineering_snapshot is not None:
        engineering_quadrant = {
            "leetcode_score": engineering_snapshot["leetcode_score"],
            "github_score": engineering_snapshot["github_score"],
            "quadrant_label": engineering_snapshot["quadrant_label"],
            "description": engineering_snapshot["description"],
        }
        company_readiness = engineering_snapshot.get("company_readiness", [])[:MAX_COMPANY_READINESS_ENTRIES]

    active_goals = await _get_active_goals(db, user_id)
    recent_job_matches = await _get_recent_job_matches(db, user_id)

    source_freshness = await compute_source_freshness(db, user_id)
    evidence_coverage = compute_evidence_coverage(source_freshness)

    # Legacy reconciliation of top_skills removed (now done upstream)
    # top_skills = reconcile_skill_confidence(top_skills, claim_risk_details, timeline_plausibility_notes)

    # Legacy portfolio narrative removed
    # portfolio_narrative_report = await get_latest_portfolio_narrative(db, user_id)
    # portfolio_narrative = (
    #     PortfolioNarrativeFacts(
    #         narrative=portfolio_narrative_report.narrative,
    #         testing_pattern=portfolio_narrative_report.testing_pattern,
    #         collaboration_pattern=portfolio_narrative_report.collaboration_pattern,
    #         specialization=portfolio_narrative_report.specialization,
    #         biggest_weakness=portfolio_narrative_report.biggest_weakness,
    #         analysis_degraded=portfolio_narrative_report.analysis_degraded,
    #     )
    #     if portfolio_narrative_report is not None and portfolio_narrative_report.eligible
    #     else None
    # )

    return IdentityFacts(
        top_skills=top_skills,
        role_fit=role_fit,
        role_fit_evidence_hash=evidence_hash,
        resume_score=resume_score,
        resume_grade=resume_grade,
        github_summary=github_summary,
        github_progress=github_progress,
        architecture_maturity=architecture_maturity,
        technology_depth_highlights=technology_depth_highlights,
        technology_breadth=technology_breadth,
        leetcode_summary=leetcode_summary,
        leetcode_topic_mastery=leetcode_topic_mastery,
        engineering_quadrant=engineering_quadrant,
        company_readiness=company_readiness,
        coverage_gaps={k: v for k, v in coverage_gaps.items() if k != "timeline_plausibility_notes"},
        timeline_plausibility_notes=timeline_plausibility_notes,
        active_goals=active_goals,
        recent_job_matches=recent_job_matches,
        claim_risk_details=claim_risk_details,
        source_freshness=source_freshness,
        evidence_coverage=evidence_coverage,
        # portfolio_narrative=portfolio_narrative,
    )