"""add_tier_to_github_analysis

Revision ID: 33109497beb1
Revises: c9d4e2f8a1b3
Create Date: 2026-07-28 06:20:46.067361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33109497beb1'
down_revision: Union[str, Sequence[str], None] = 'c9d4e2f8a1b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('github_project_analysis', sa.Column('tier', sa.String(length=50), server_default='experiment', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('github_project_analysis', 'tier')
    # ### end Alembic commands ###
